add curl support

diff --git a/getnode b/getnode
--- a/getnode
+++ b/getnode
@@ -75,11 +75,17 @@ For more advanced tools to manage Node installations see:
 [nave](https://github.com/isaacs/nave) by
 [Isaac Z. Schlueter](https://github.com/isaacs).
 
+Both nvm and nave can be used to manage many different Node versions installed
+simultaneously on the same system.  Getnode on the other hand can be used to
+install one version of Node on many different systems.  So if you need to run
+a specific version of Node in a heterogeneous environment of incompatible
+systems where binary deployment is not an option then Getnode may be for you.
+
 PREREQUISITES
 -------------
-Getnode uses Wget to download the source code of Node, Tar to extract it and
-Make to build it.  Building Node requires essential development tools like
-Make and a C++ compiler, Python version 2.4 or higher and a development
+Getnode uses cURL or Wget to download the source code of Node, Tar to extract
+it and Make to build it.  Building Node requires essential development tools
+like Make and a C++ compiler, Python version 2.4 or higher and a development
 version of the SSL library.  Testing Node requires cURL.
 
 Most of those tools are probably installed by default on any modern system.
@@ -91,6 +97,12 @@ to have everything needed to build and test Node.
 
 See more info on
 [Node's dependencies](https://github.com/ry/node/wiki/Installation).
+
+BUGS
+----
+If you find any bugs or have any suggestion, please use
+[the issue tracking system](https://github.com/rsp/getnode/issues)
+or fork the project on GitHub, fix it and send me a pull request.
 
 TODO
 ----
@@ -135,6 +147,17 @@ function askcontinue {
         [Yy][Ee][Ss]);;
         *) error "Aborting";;
     esac
+}
+function find_get_command {
+    get_program=$(which curl) && {
+        get_command="$get_program -f -O"
+        return
+    }
+    get_program=$(which wget) && {
+        get_command="$get_program"
+        return
+    }
+    return 1
 }
 function find_sha1_command {
     digest_length=40
@@ -187,7 +210,8 @@ fi
 if [ -f $file ]; then
     warn "File $file already exists - skipping download"
 else
-    wget $url
+    find_get_command || error "You need to have curl or wget installed in PATH"
+    $get_command $url || error "Download failed"
 fi
 if [ ! -f $file ]; then
     error "File $file not found - download failed"
