add SHA-1 checksum support

diff --git a/getnode b/getnode
--- a/getnode
+++ b/getnode
@@ -63,6 +63,10 @@ ABOUT GETNODE
 Getnode is a shell script written by Rafał Pocztarski to speed up Node
 deployments.
 
+It downloads the source code of a given version of Node, calculates SHA-1
+checksum and asks for approval.  Then it tries to configure, build and test
+Node.  Currently it doesn't install but does everything except `make install`.
+
 PREREQUISITES
 -------------
 Getnode uses Wget to download the source code of Node, Tar to extract it and
@@ -84,9 +88,11 @@ TODO
 ----
 There is still a lot to do to make this script more useful.
 
-The default installation prefix will change and more shortcuts will be added.
-
-There should be an option to build without SSL and maybe without testing.
+* The default installation prefix will change and more shortcuts will be added.
+* There should be an option to build without SSL and maybe without testing.
+* There will be an option to automatically `make install`.
+* There will be option to automatically answer Yes to any question.
+* There will be a way to supply the correct SHA-1 checksum to verify against.
 
 This is an early version, use it at your own risk.
 END_DESCRIPTION
@@ -121,6 +127,22 @@ function askcontinue {
         [Yy][Ee][Ss]);;
         *) error "Aborting";;
     esac
+}
+function find_sha1_command {
+    digest_length=40
+    hash_program=$(which openssl) && {
+        hash_command="$hash_program dgst -sha1"
+        return
+    }
+    hash_program=$(which sha1sum) && {
+        hash_command="$hash_program"
+        return
+    }
+    hash_program=$(which shasum) && {
+        hash_command="$hash_program -a1"
+        return
+    }
+    return 1
 }
 
 case "$1" in
@@ -162,6 +184,17 @@ fi
 if [ ! -f $file ]; then
     error "File $file not found - download failed"
 fi
+
+if find_sha1_command; then
+    warn "Running: $hash_command < $file"
+    hashline=`$hash_command < $file` || error "Error running $hash_command"
+    realhash=${hashline%% *}
+    warn "SHA-1 checksum: $realhash"
+else
+    warn "Cannot find any program to calculate SHA-1 checksum!"
+fi
+askcontinue
+
 tar xzvf $file || error "Error extracting $file"
 if [ ! -d $dir ]; then
     error "Directory $dir not found - extraction failed"
